name: Build Minecraft Mod

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-output
          path: build/libs/*.jar

      - name: Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: "v${{ github.run_number }}"
          body_path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
